name: "Армения"
code: "AM"
priority: 4

license_plate_formats:
  - name: "standard"
    regex: '^[ABEKMHOPCTYX]{2}\d{3}[ABEKMHOPCTYX]{2}$'

valid_characters:
  letters: "ABEKMHOPCTYX"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "O"
    "1": "I"
    "8": "B"
  common_mistakes: []

stop_words:
  - "TEST"

invalid_sequences:
  - "AAAA"
