name: "Азербайджан"
code: "AZ"
priority: 5

license_plate_formats:
  - name: "standard"
    regex: '^\d{2}[A-Z]{2}\d{3}$'

valid_characters:
  letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZАВЕКМНОРСТУХ"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "O"
    "1": "I"
    "6": "G"
    "8": "B"
  common_mistakes: []

stop_words:
  - "TEST"

invalid_sequences:
  - "1234"
