name: "Казахстан"
code: "KZ"
priority: 3
uses_cyrillic: false
strip_characters: "- _"
stop_words: ["TEST", "SAMPLE"]
max_repeated: 4

license_plate_formats:
  - name: "standard_car"
    regex: "^[0-9]{3}[A-Z]{2}[0-9]{2}$"
    description: "Стандартный номер"

valid_characters:
  letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  digits: "0123456789"

corrections:
  common_mistakes:
    - from: "0"
      to: "O"
    - from: "1"
      to: "I"
    - from: "8"
      to: "B"
