name: "Казахстан"
code: "KZ"
priority: 3

license_plate_formats:
  - name: "standard"
    regex: '^\d{3}[ABEKMHOPCTYX]{2}\d{2}$'
  - name: "police"
    regex: '^[ABEKMHOPCTYX]{2}\d{3}\d{2}$'

valid_characters:
  letters: "ABEKMHOPCTYX"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "O"
    "1": "I"
    "4": "A"
    "6": "B"
    "8": "B"
  common_mistakes:
    - from: "D"
      to: "O"

stop_words:
  - "TEST"

invalid_sequences:
  - "0000"
