name: "Российская Федерация"
code: "RU"
priority: 1
uses_cyrillic: true
strip_characters: "- _"
stop_words: ["TEST", "SAMPLE"]
max_repeated: 4

license_plate_formats:
  - name: "standard_car"
    regex: "^[ABEKMHOPCTYXАВЕКМНОРСТУХ][0-9]{3}[ABEKMHOPCTYXАВЕКМНОРСТУХ]{2}[0-9]{2,3}$"
    description: "Автомобиль"
  - name: "transit"
    regex: "^[ABEKMHOPCTYXАВЕКМНОРСТУХ]{2}[0-9]{6}$"
    description: "Транзитный номер"
  - name: "trailer"
    regex: "^[0-9]{4}[ABEKMHOPCTYXАВЕКМНОРСТУХ]{2}[0-9]{2,3}$"
    description: "Прицеп"
  - name: "motorcycle"
    regex: "^[0-9]{4}[ABEKMHOPCTYXАВЕКМНОРСТУХ]{2}[0-9]{2,3}$"
    description: "Мотоцикл"

valid_characters:
  letters: "ABEKMHOPCTYXАВЕКМНОРСТУХ"
  digits: "0123456789"

corrections:
  common_mistakes:
    - from: "0"
      to: "О"
    - from: "1"
      to: "Т"
    - from: "8"
      to: "В"
    - from: "5"
      to: "S"
    - from: "3"
      to: "З"
