name: "Туркменистан"
code: "TM"
priority: 6

license_plate_formats:
  - name: "standard"
    regex: '^[A-Z]{2}\d{3}[A-Z]{2}$'

valid_characters:
  letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "O"
    "1": "I"
    "4": "A"
    "7": "Z"
    "8": "B"
  common_mistakes: []

stop_words:
  - "TEST"

invalid_sequences:
  - "AAAA"
