name: "Казахстан"
code: "KZ"
priority: 2

license_plate_formats:
  - name: "standard_car"
    regex: '^\d{3}[АВЕКМНОРСТУХ]{3}\d{2}$'
  - name: "transit"
    regex: '^\d{3}[АВЕКМНОРСТУХ]{2}\d{2}$'

valid_characters:
  letters: "АВЕКМНОРСТУХ"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "О"
    "1": "I"
    "3": "З"
    "8": "В"

stop_words:
  - "TEST"
  - "SAMPLE"

invalid_sequences:
  - "0000"
