name: "Российская Федерация"
code: "RU"
priority: 1

license_plate_formats:
  - name: "standard_car"
    regex: '^[АВЕКМНОРСТУХ]{1}\d{3}[АВЕКМНОРСТУХ]{2}\d{2,3}$'
  - name: "transit"
    regex: '^[АВЕКМНОРСТУХ]{2}\d{6}$'
  - name: "trailer"
    regex: '^\d{4}[АВЕКМНОРСТУХ]{2}\d{2,3}$'

valid_characters:
  letters: "АВЕКМНОРСТУХ"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "О"
    "1": "Т"
    "3": "З"
    "4": "А"
    "6": "Б"
    "8": "В"
  common_mistakes:
    - from: "D"
      to: "О"

stop_words:
  - "ТЕСТ"
  - "SAMPLE"

invalid_sequences:
  - "0000"
  - "ЕЕЕЕ"
