name: "Российская Федерация"
code: "RU"
priority: 1
alphabet: "cyrillic"

license_plate_formats:
  - name: "standard_car"
    regex: "^[ABEKMHOPCTYX]{1}\d{3}[ABEKMHOPCTYX]{2}\d{2,3}$"
    description: "Автомобиль"
  - name: "transit"
    regex: "^[ABEKMHOPCTYX]{2}\d{6}$"
    description: "Транзитный номер"
  - name: "trailer"
    regex: "^\d{4}[ABEKMHOPCTYX]{2}\d{2,3}$"
    description: "Прицеп/мотоцикл"

valid_characters:
  letters: "ABEKMHOPCTYXАВЕКМНОРСТУХЗБ"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "О"
    "1": "Т"
    "3": "З"
    "4": "А"
    "6": "Б"
    "8": "В"
  latin_to_cyrillic:
    "A": "А"
    "B": "В"
    "C": "С"
    "E": "Е"
    "H": "Н"
    "K": "К"
    "M": "М"
    "O": "О"
    "P": "Р"
    "T": "Т"
    "X": "Х"
    "Y": "У"
  common_mistakes:
    - from: "D"
      to: "О"

stop_words:
  - "ТЕСТ"
  - "SAMPLE"

invalid_sequences:
  - "0000"
  - "EEEE"
