name: "Беларусь"
code: "BY"
priority: 8
min_length: 7
max_length: 9

license_plate_formats:
  - name: "standard_car"
    regex: '^\d{4}[ABEKMHOPCTYX]{2}-\d$'
  - name: "standard_compact"
    regex: '^\d{4}[ABEKMHOPCTYX]{2}\d$'

valid_characters:
  letters: "ABEKMHOPCTYX"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "О"
    "1": "I"
    "3": "З"
    "4": "А"
    "8": "В"
  letter_to_digit:
    "О": "0"
    "I": "1"
    "З": "3"
    "А": "4"
    "В": "8"
  common_mistakes:
    - from: "O"
      to: "О"

stop_words:
  - "TEST"
  - "SAMPLE"

invalid_sequences:
  - "0000"
  - "AAAA"
