name: "Республика Казахстан"
code: "KZ"
priority: 3

license_plate_formats:
  - name: "standard"
    regex: '^\d{3}[A-Z]{2}\d{2}$'
  - name: "region_prefix"
    regex: '^KZ\d{3}[A-Z]{2}\d{2}$'

valid_characters:
  letters: "ABCEHKMOPTXY"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "O"
    "1": "I"
    "4": "A"
    "8": "B"
  letter_to_digit:
    "O": "0"
    "I": "1"
  common_mistakes:
    - from: "Q"
      to: "O"

stop_words:
  - "TEST"
  - "SAMPLE"

invalid_sequences:
  - "000"
  - "AAA"

min_length: 7
max_length: 10
