name: "Российская Федерация"
code: "RU"
priority: 1

license_plate_formats:
  - name: "standard_car"
    regex: '^[ABEKMHOPCTYX]{1}\d{3}[ABEKMHOPCTYX]{2}\d{2,3}$'
  - name: "transit"
    regex: '^[ABEKMHOPCTYX]{2}\d{6}$'
  - name: "trailer"
    regex: '^\d{4}[ABEKMHOPCTYX]{2}\d{2,3}$'

valid_characters:
  letters: "ABEKMHOPCTYX"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "О"
    "1": "Т"
    "4": "А"
    "6": "Б"
    "8": "В"
  letter_to_digit:
    "О": "0"
    "Т": "1"
    "В": "8"
  common_mistakes:
    - from: "D"
      to: "О"
    - from: "Q"
      to: "О"

stop_words:
  - "ТЕСТ"
  - "SAMPLE"

invalid_sequences:
  - "0000"
  - "EEEE"

min_length: 6
max_length: 10
