name: "Украина"
code: "UA"
priority: 4

license_plate_formats:
  - name: "standard"
    regex: '^[АВЕІКМНОРСТХABCEIKMHOPCTX]{2}\d{4}[АВЕІКМНОРСТХABCEIKMHOPCTX]{2}$'
  - name: "diplomatic"
    regex: '^\d{3}[A-Z]{2}\d{2}$'

valid_characters:
  letters: "АВЕІКМНОРСТХABCEIKMHOPCTX"
  digits: "0123456789"

corrections:
  digit_to_letter:
    "0": "О"
    "1": "І"
    "3": "З"
    "4": "А"
    "8": "В"
  letter_to_digit:
    "О": "0"
    "І": "1"
    "З": "3"
  common_mistakes:
    - from: "D"
      to: "О"

stop_words:
  - "TEST"
  - "SAMPLE"

invalid_sequences:
  - "0000"
  - "AAAA"

min_length: 8
max_length: 10
